server:
  port: 8088
  servlet:
    context-path: /mq
    session:
      timeout: 30
spring:
  skafka:
    # 指定kafka 代理地址，可以多个
    bootstrap-servers: 172.23.123.57:9092,172.23.123.57:9093,172.23.123.57:9094
    #生产者
    producer:
      retries: 0
      # 每次批量发送消息的数量
#      batch-size: 16384
#      buffer-memory: 33554432
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: -1
    #消费者
    consumer:
      group-id: program_A_consumer_group
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer