server:
  port: 8080
  servlet:
    context-path: /rocketmq
    session:
      timeout: 30
rocketmq:
  # 指定namesrv地址
  namesrvAddr: 172.23.122.211:9877;172.23.122.211:9876
  #生产者group名称
  producerGroupName: producerGroupName
  #事务生产者group名称
  transactionProducerGroupName: order
  #生产者实例名称
  producerInstanceName: user_producer_instance
  #事务生产者实例名称
  producerTraninstanceName: user_producer_transacition
  #启动的时候是否消费历史记录
  enableHistoryConsumer: false
  #消费者集合
  consumerList:
    - name: AFC-FLOW
      enable: true
      groupName: PCI-MICS
      topic: broker-a~*;broker-b~*;broker-c~*
      # 指定namesrv地址
      namesrvAddr: 172.23.122.211:9876
      #广播消费
      consumerBroadCasting: false
      #一次最大消费多少数量消息
      consumerBatchMaxSize: 1
      #启动顺序消费
      enableOrderConsumer: false
      consumeThreadMin: 20
      consumeThreadMax: 64



