

imc:
  rocketmq:
    namesrv-addr: 172.23.122.211:9876
    #消费者集合
    consumer-list:
      -
        name: AFC-FLOW
        enable: true
        group-name: PCI-MICS
        topic: AFC-FLOW
        handler-class-name: com.pci.imc.streaming.mq.handler.impl.PflowMessagePreHandler
      -
        name: CCTV-FLOW
        enable: true
        group-name: CCTV-FLOW
        topic: CCTV-FLOW
        handler-class-name: com.pci.imc.streaming.mq.handler.impl.CctvMessageHandler
    #生产者group
    producer-Group-Name: producerGroupName
    #事务生产者group名称
    transaction-Producer-Group-Name: order_transaction
    #生产者实例名称
    producer-Instance-Name: user_producer_instance
    #事务生产者实例名称
    producer-TranInstance-Name: user_producer_transacition
    #一次最大消费多少数量消息
    consumerBatchMaxSize: 1
    #广播消费
    consumerBroadcasting: false
    #消费的topic：tag
    subscribe[0]: user-topic:white
    #启动的时候是否消费历史记录
    enableHistoryConsumer: false
    #启动顺序消费
    enableOrderConsumer: false
server:
  port: 8080
  context-path: /rocketmq
